### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'LINEAR'

### ISSUE THREAD

**Issue by LouisDo2108** [USTCL/DCNet#2]
Thank you for your excellent work. I discover this bug when reproducing your result: 

```
~/miniconda3/envs/dcnet/lib/python3.9/site-packages/detectron2/data/transforms/transform.py", line 46, in ExtentTransform
def __init__(self, src_rect, output_size, interp=Image.LINEAR, fill=0):
AttributeError: module 'PIL.Image' has no attribute 'LINEAR'
```
According to this issue: https://github.com/facebookresearch/detectron2/issues/5010, "BILINEAR" should be used instead of "LINEAR".

Best regards,
Tuan-Luc Huynh

**Comment by CatByteDance** [comment]
same problem

**Comment by CatByteDance** [comment]
Hello, did you solve this? @LouisDo2108

**Comment by LouisDo2108** [comment]
Hi @CatByteDance, you can temporarily fix this by replacing `interp=Image.LINEAR` with `interp=Image.BILINEAR` in the above file. I know this is not the recommended way, but I hope this could help you.

**Comment by CatByteDance** [comment]
Thanks for your reply! @LouisDo2108 , the bug can be solved according to your suggestion, but some other bugs came out. I guess it maybe the disconsistency problem between detectron2 version and PyTorch version for I did not follow the official steps. Have you succusfully reproduce the result after you changed `interp=Image.LINEAR` to `interp=Image.BILINEAR` following the official steps? @LouisDo2108

**Comment by LouisDo2108** [comment]
Hi @CatByteDance , I have no problem after fixing the previous bug, or perhaps I have forgotten what I fixed. You should always follows the official steps.
